services:
  - type: web
    name: telegram-auto-forwarder
    env: node
    buildCommand: |
      npm install
      mkdir -p telegram_session
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SOURCE_GROUP
        value: ceeVIPpolycarp22334455
      - key: TARGET_GROUP
        value: +JyAcm_mp4GplN2Q5
      - key: POSTER_USERNAME
        value: policeesupport
      - key: ADMIN_TOKEN
        generateValue: true
